Task 3
cartotien/Test-Guru pull request #3
Opened 2022-09-15 15:55 UTC by cartotien

2022-09-16 06:21 UTC, VidgarVii requested changes

2022-09-16 06:21 UTC, VidgarVii commented on db/seeds.rb
> +categories = Category.create(
лучше использовать `create!` - метод бросит исключение, если запись не создастся
сразу будет видно, если что-то пошло не так

2022-09-16 06:21 UTC, VidgarVii commented on db/seeds.rb
> +Question.create(
Учитывая кол-во тестов, тут очень мало вопросов и совсем нет ответов. Такое не возможно будет тестировать

2022-09-16 06:21 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins('JOIN users ON tests.author_id = users.id')
по ТЗ надо вернуть пройденные тесты, а не авторские

задачку про "пройденные тесты" правильно решать через соединительную таблицу
нужно добавить модель, к примеру `Result` или `TestsUser` и соответсвенную таблицу (`tests_users` или `results`)... или `TestPassage` и `test_passages`
в общем нужны "промежуточная модель" и "соединительная таблица"
такая таблица ("соединительная") обычно в минимальном виде хранит два внешних ключа на таблицы, которые соединяет
когда пользователь проходит тест в этой таблице должна появляться запись содержащая соответсвенно ай-ди этого пользователя и ай-ди пройденного теста
(подробней можешь посмотреть в документации к рельсам про соединительные модели, таблицы)

2022-09-17 15:52 UTC, VidgarVii requested changes

2022-09-17 15:52 UTC, VidgarVii commented on app/models/test.rb
> +  has_and_belongs_to_many :users
1 ассоциации пишут вверху класса
2 в этом ТЗ не надо объявлять ассоциации. Потом сделаем сразу верно. А текущая ошибочна

2022-09-17 15:52 UTC, VidgarVii commented on db/migrate/20220915203107_create_join_table_tests_users.rb
> +    create_join_table :tests, :users do |t|
лучше создавать сразу модель. Будет возможность для расширения

2022-09-17 15:52 UTC, VidgarVii commented on app/models/user.rb
> +  end
да верная ассоциация поможет написать код так. Но пока нам надо научиться сделать это средствами SQL, чтобы потом не появлялись вопросы типо, как получить что-то из текущей таблицы по условию соединительной таблицы. И пока без ассоциаций

2022-09-18 16:45 UTC, VidgarVii requested changes

2022-09-18 16:45 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins('JOIN test_passages ON test_id')
не работает. Вспомни как надо писать запрос для объединения таблиц

2022-09-18 16:45 UTC, VidgarVii commented on db/migrate/20220917135727_create_test_passages.rb
> +      t.references :user, foreign_key: true
стоит везде добавить Null false
Не думаю, что запись о пройденном тесте в таблице без юзера и теста будет актуальной

2022-09-18 16:51 UTC, cartotien commented on app/models/user.rb
> +    Test.joins('JOIN test_passages ON test_id')
> не работает. Вспомни как надо писать запрос для объединения таблиц

 Test Load (0.1ms)  SELECT "tests".* FROM "tests" JOIN test_passages ON test_id WHERE "tests"."level" = ? AND "test_passages"."user_id" = ?  [["level", 1], ["user_id", 1]]                      
 => []

2022-09-18 16:52 UTC, cartotien commented on app/models/user.rb
> +    Test.joins('JOIN test_passages ON test_id')
Полагаю, что если выдается пустой массив, то запрос выполнился

2022-09-18 17:11 UTC, cartotien commented on app/models/user.rb
> +    Test.joins('JOIN test_passages ON test_id')
Оттестировал, выдаются вообще все тесты с данным уровнем при джойне без объявления ключей, которые джойнят

2022-09-19 14:27 UTC, merged